### ISSUE TITLE
运行“./gtund -c gtund.conf”遇错

### ISSUE THREAD

**Issue by luckypoem** [ICKelin/gtun#3]
hi.

[root@host gtund]# ./gtund -c gtund.conf
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6525d9]

goroutine 1 [running]:
github.com/ICKelin/gtun/gtund.NewInterface(0x0, 0xc420016d60, 0xc, 0xc420016c80, 0xf, 0xb, 0xc420022d60, 0xc420094100)
	/root/go/gopath/src/github.com/ICKelin/gtun/gtund/iface.go:29 +0xb9
github.com/ICKelin/gtun/gtund.Main()
	/root/go/gopath/src/github.com/ICKelin/gtun/gtund/main.go:38 +0x2bc
main.main()
	/root/gtun-by-ICKelin/main/gtund/gtund.go:39 +0x20
[root@host gtund]#

怎么解决？

**Comment by ICKelin** [comment]
@luckypoem 这个是interface配置项的问题
```
name="us-node-1-1"

[server]
token="gtund-cs-goken"
listen=":9091"
auth_key="gtun-cs-token"
nameservers=["8.8.8.8", "8.8.4.4"]
route_url="http://www.ipdeny.com/ipblocks/data/countries/us.zone"

[dhcp]
cidr="100.64.240.1/24"
gateway="100.64.240.1"
nameserver="8.8.8.8"

[interface]
istap=false
```

**[interface]
istap=false**

**Comment by luckypoem** [comment]
hi.

[root@host gtund]# ./gtund -c gtund.conf
2019/09/06 11:26:00.212033 main.go:70 [W] run reverse fail: open reverse.policy: no such file or directory
2019/09/06 11:26:00.212891 server.go:258 [W] only support for ipv4
2019/09/06 11:26:00.213445 registry.go:81 [W] disconnect with registry: dial tcp 127.0.0.1:9092: connect: connection refused
2019/09/06 11:26:03.215032 registry.go:81 [W] disconnect with registry: dial tcp 127.0.0.1:9092: connect: connection refused
2019/09/06 11:26:03.970511 server.go:258 [W] only support for ipv4
2019/09/06 11:26:06.215800 registry.go:81 [W] disconnect with registry: dial tcp 127.0.0.1:9092: connect: connection refused
2019/09/06 11:26:09.216633 registry.go:81 [W] disconnect with registry: dial tcp 127.0.0.1:9092: connect: connection refused
2019/09/06 11:26:11.906541 server.go:258 [W] only support for ipv4
2019/09/06 11:26:12.217418 registry.go:81 [W] disconnect with registry: dial tcp 127.0.0.1:9092: connect: connection refused
^C
[root@host gtund]#

"connection refused"是怎么造成的？如何解决？

**Comment by ICKelin** [comment]
@luckypoem 不配置registry需要把gtund.conf以下内容去掉：
```
[registry]
interval=3
timeout=5
addr="127.0.0.1:9092"
token="gtund-sr-token"
must=false

```

**Comment by luckypoem** [comment]
用你这个vpn翻墙成功，不过有点不稳定，运行大概2个小时，就会翻墙失败，只好重新运行客户端的相关命令才行。如何能改进稳定性呢？
