### ISSUE TITLE
quIC转发

### ISSUE THREAD

**Issue by mosquitood** [ICKelin/gtun#6]
麻烦 配置文件贴一下

**Comment by ICKelin** [comment]
了解了些些背景，在有专线前提下，udp直接使用iptables做转发是最简单的方式。

`iptables -t nat -I PREROUTING -p udp --dport 33790 -j DNAT --to 专线出口局域网IP:3379`

这样就可以实现最简单的udp流量转发，比使用nginx要简单，而且udp无连接概念，没有提前握手，预建连等操作。

---------------------------------------------------------------
gtun本身是个提供客户端的ip转发项目，是基于流量劫持的机制，如果只希望使用端口转发，有两种选择：
1. 使用上述的iptables+专线做转发
2. 仅使用gtun服务端，客户端把流量劫持的模块改成端口监听，即可实现端口转发。
